{% set name = "mplcairo" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mplcairo-{{ version }}.tar.gz
  sha256: eac1d408cf4101db0ab4d0d57e6c3840bd5434818dc6cd295fc923062f9180d5

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.8.0                       # [build_platform != target_platform]
    - cairo >=1.13.1                         # [build_platform != target_platform]
    - pycairo >=1.16.0                       # [build_platform != target_platform]
    - expat                                  # [build_platform != target_platform]
    - glib                                   # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - xorg-xorgproto                         # [linux and build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - setuptools >=62
    - setuptools-scm >=6.2
    - pybind11 >=2.8.0
    # MIN_CAIRO_VERSION in setup.py
    - cairo >=1.13.1
    - pycairo >=1.16.0
    - pip
    # the following are needed to find cairo with pkg-config
    - expat
    - glib
    - zlib
    - xorg-xorgproto  # [linux]
  run:
    - python
    - matplotlib-base >=2.2
    - pillow
    # MIN_CAIRO_VERSION in setup.py
    - cairo >=1.13.1
    - pycairo >=1.16.0

test:
  imports:
    - mplcairo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matplotlib/mplcairo
  summary: A (new) cairo backend for Matplotlib.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://github.com/matplotlib/mplcairo/blob/main/README.rst
  dev_url: https://github.com/matplotlib/mplcairo

extra:
  recipe-maintainers:
    - xylar
